### ISSUE TITLE
Utilize Loki Network

### ISSUE THREAD

**Issue by majestrate** [medium-isp/medium#26] opened 2019-07-22 12:52 UTC
[lokinet](https://github.com/loki-project/loki-network) is an ip layer onion router that was made to run on soho routers, you can push all lan traffic over it since it exposes a tun interface instead of providing application tunnels. you don't need the coin part to run a network. 

Main advantages over i2p:

* bidirectional tunnels, this means better performance and faster tunnel build times.
* client/server separation, this also brings better performance as i2p already organically shapes itself this way anyways. ( you COULD make it full p2p if you really really wanted to....)

Pitfalls:

* currently it has a very small user base
* packets may drop without warning (this is from a bug but we're working on it)

**Comment by podivilov** [comment] 2019-07-22 14:16
Welcome to the Medium community, @majestrate!

Thanks for your message.

What do you mean by "packets may drop without warning"? It's a very important issue, I guess.

**Comment by majestrate** [comment] 2019-07-22 14:17
there is a bug in the current master branch of lokinet that we are working on sorting out before next release that causes packet loss when there shouldn't be packet loss.

**Comment by podivilov** [comment] 2019-07-22 14:22
Hope it will be fixed as soon as possible.

We are discussed about using Yggdrasil as secondary transport for Medium. It's OK to use lokinet as a replacement for Yggdrasil in that context? I mean that we are currently I2P as primary transport, so lokinet is a i2p fork (am I right?), ain't absurd that we will use two I2P instances in one network..?

**Comment by majestrate** [comment] 2019-07-22 14:28
lokinet is more like i2p redone from square one for the purposes of being faster, it's not a fork of i2p but its design is loosely inspired by i2p. lokinet is its own thing. it's more of an i2p replacement than an yggdrasil replacement.

**Comment by podivilov** [comment] 2019-07-22 14:33
It's a really very interesting thing. You said that lokinet's speed is more faster than I2P can provide (lokinet faster than I2P by design).

Can you describe the technical details that allowed to speed up your network in comparsion with I2P?

**Comment by majestrate** [comment] 2019-07-22 15:21
the things that actually make it faster:

* lighter cryptographic primitives
* bidirectional tunnels lower the rate of change in latency (jitter) which leads to higher throughput with tcp over the network.
* the client/server separation really helps remove bottlenecking and lower the latency.

the cryptographic primitives used really help speed stuff up, they were chosen for their speed and security. 

* `chacha20` for symmetric encryption, vs i2p's `AES ECB` (ew)
* `blake2` for hash and message authentication tags, vs i2p's `sha256`
* `x25519` for key exchanges, vs i2p's `elgamal`
* `blake2+x25519+sntrup` is used for hidden service traffic, vs i2p's `elgamal+aes`
* `ed25519` variant using `blake2` instead of sha512 for signature, vs the many varying signatures used in i2p.

**Comment by podivilov** [comment] 2019-07-22 17:19
You said that `bidirectional tunnels` is advantage over I2P. As far I know, I2P also has a bidirectional tunnels. Am I wrong?

Things you said about are sounds good. But what about % comparsion of speed (your network versus I2P)? Can you provide some numbers?

Thanks.

**Comment by majestrate** [comment] 2019-07-22 17:28
i2p uses unidirectional tunnels but can do bidirectional using 2 unidirectional tunnels on the same set of peers as a workaround. speed wise i don't have any easy ways to compare i2p's throughput and lokinet's throughput at the moment but i conjecture that it would be on average at least a regular throughput of 100KB/s of tcp/ip across a full hidden service path (4 + 4 - 1), this may change (going up or down) depending on various factors like network capacity.

**Comment by l-n-s** [comment] 2019-07-23 10:25
I've barely touched it, all I can say - it works fine and stable.

**Comment by podivilov** [comment] 2019-07-23 10:28
@l-n-s It is a good idea to replace I2P with Lokinet or add Lokinet as secondary transport?

**Comment by majestrate** [comment] 2019-07-23 12:00
probably better to add as secondary transport.

**Comment by podivilov** [comment] 2019-07-23 12:35
@majestrate Sounds good. But the question how to route traffic to separated transports is open.

**Comment by podivilov** [comment] 2019-07-25 10:25
@majestrate, I have an idea how LokiNet can be added to Medium.

When user just connects to Medium Wi-Fi hotspot, captive portal being shown.
Captive portal should contain text fields with IP of local computer connected to I2P and LokiNet, with proxies on separated ports (e.g. 10.0.0.1:5555 for I2P and 10.0.0.1:5556 for LokiNet), so user can just use this data to setup own browser proxy to use one of this networks.

What do you think about this?

**Comment by podivilov** [comment] 2019-07-25 12:47
Something like

![](http://i.imgur.com/MiUah1q.png)

**Comment by majestrate** [comment] 2019-07-25 12:56
the thing is lokinet operates at the network layer (layer 3) which is a layer below what i2p and tor operate at. not sure if this works.

**Comment by podivilov** [comment] 2019-07-25 13:04
@majestrate, LokiNet works like Yggdrasil? (it also uses OSI layer 3)

**Comment by majestrate** [comment] 2019-07-25 13:38
it's both, it's OSI layer 3 (like yggdrasil) that provides onion routing layer over the internet like i2p.

**Comment by podivilov** [comment] 2019-07-25 14:12
@majestrate, so, what's problem?

**Comment by majestrate** [comment] 2019-07-25 14:17
lokinet doesn't do `host:port` it does IPs

**Comment by podivilov** [comment] 2019-07-25 14:40
@majestrate, didn't understand. Lokinet doesn't have a proxy?

**Comment by majestrate** [comment] 2019-07-25 14:52
lokinet is a layer 3 "proxy" like a vpn tunnel.

**Comment by podivilov** [comment] 2019-07-25 14:54
@majestrate, I'm a little bit confused. What's a problem to use lokinet as proxy in Medium? Like http proxy of i2pd.

**Comment by majestrate** [comment] 2019-07-25 14:55
lokinet doesn't provide layer 4 proxy like socks or http, only layer 3 tun adapter proxy.

**Comment by podivilov** [comment] 2019-07-25 14:56
It's OK to use squid or tinyproxy to ogranize that. There is no visible problem for me. Maybe I wrong?

**Comment by majestrate** [comment] 2019-07-25 14:56
you could but that is really limiting. you can't do udp that way.

**Comment by podivilov** [comment] 2019-07-25 14:58
AFAIK, we can't use lokinet in Medium because it doesn't provide any kind of proxy to use them as OSI 4 layer transport.

**Comment by podivilov** [comment] 2019-07-25 14:59
Do you have any idea how to utilize lokinet in Medium?

**Comment by podivilov** [comment] 2019-08-05 12:56
@majestrate, LokiNet will be never used as Medium transport.

**Closed by podivilov** 2019-08-05 12:56 UTC

**Comment by majestrate** [comment] 2019-08-05 13:00
okay cool, as just seeing if it was relevant for you use case.

**Comment by podivilov** [comment] 2019-08-05 13:01
@majestrate thanks for the participation! We are will now use Yggdrasil as primary and no secondary transport.
